//
// Created by yasen on 6/26/18.
//

#ifndef RASTERGRAPHICS_COMMAND_H
#define RASTERGRAPHICS_COMMAND_H
enum COMMAND {
    GRAYSCALE = 1,
    MONOCHROME = 2,
    NEGATIVE = 3,
    ROTATELEFT = 4,
    ROTATERIGHT = 5,
};
#endif //RASTERGRAPHICS_COMMAND_H
